baseurl: ''
url: 'https://dratatianaleal.com'
name: Tatiana Leal
email: asistentetatianaleal@gmail.com
maps: https://maps.app.goo.gl/bvbNFb82J7X3s1q16
direccion: "Torre Magna PI, Av Suba #114 - 59 Piso 6, Cons G14, Bogotá"
telefono: 3222010384

# Información del autor y social
author:
  name: Tatiana Leal
  email: asistentetatianaleal@gmail.com
  instagram: https://www.instagram.com/dratatianaleal/
  facebook: https://www.facebook.com/Dra.TatianaLealSandoval
  youtube: https://www.youtube.com/channel/UCxF-X7in4xUFxYYwCMyC5OQ
  job_title: "Especialista en medicina estética y láser"
  bio: "La Dra. Tatiana Leal es una destacada especialista en Medicina Estética..."

# SEO Configuration
title: Doctora Tatiana Leal
tagline: "Especialista en medicina estética y láser"
description: "Clínica de Medicina Estética especializada en rejuvenecimiento facial y corporal en Bogotá"
logo: /img/logo-tatiana-leal.webp
social:
  name: Dra. Tatiana Leal
  links:
    - https://www.instagram.com/dratatianaleal/
    - https://www.facebook.com/Dra.TatianaLealSandoval
    - https://www.youtube.com/channel/UCxF-X7in4xUFxYYwCMyC5OQ

# Publisher
publisher:
  name: Tatiana Leal
  logo: /img/logo-tatiana-leal.webp

markdown: kramdown

# Configuración de idiomas mejorada
language: "es"
default_lang: "es"
languages: ["es", "en"]
t:
  es:
    name: "Español"
    icon: "🇪🇸"
  en:
    name: "English"
    icon: "🇺🇸"
exclude_from_localization: ["css", "img", "js"]

# Configuración de URLs y colecciones
permalink: /:lang/:collection/:title/

# Valores por defecto
defaults:
  - scope:
      path: "index.html"
    values:
      redirect_to: "/es/"
  - scope:
      path: ""
    values:
      lang: "es"
      layout: "default"
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      path: "_posts/es"
    values:
      lang: "es"
      layout: "articulo"
  - scope:
      path: "_posts/en"
    values:
      lang: "en"
      layout: "articulo"
  - scope:
      path: ""
      type: "tratamientos-faciales_es"
    values:
      lang: "es"
      layout: "servicios"
  - scope:
      path: ""
      type: "tratamientos-faciales_en"
    values:
      lang: "en"
      layout: "servicios"
  - scope:
      path: ""
      type: "tratamientos-corporales_es"
    values:
      lang: "es"
      layout: "servicios"
  - scope:
      path: ""
      type: "tratamientos-corporales_en"
    values:
      lang: "en"
      layout: "servicios"
  - scope:
      path: ""
      type: "tratamientos-intimos_es"
    values:
      lang: "es"
      layout: "servicios"
  - scope:
      path: ""
      type: "tratamientos-intimos_en"
    values:
      lang: "en"
      layout: "servicios"
  - scope:
      path: ""
      type: "tecnologia_es"
    values:
      lang: "es"
      layout: "servicios"
  - scope:
      path: ""
      type: "tecnologia_en"
    values:
      lang: "en"
      layout: "servicios"
  - scope:
      path: "sitemap.xml"
    values:
      layout: null

collections:
  posts:
    output: true
    permalink: /:lang/blog/:title/
  tratamientos-faciales_es:
    output: true
    permalink: /es/tratamientos-faciales/:slug/
  tratamientos-faciales_en:
    output: true
    permalink: /en/facial-treatments/:slug/
  tratamientos-corporales_es:
    output: true
    permalink: /es/tratamientos-corporales/:slug/
  tratamientos-corporales_en:
    output: true
    permalink: /en/body-treatments/:slug/
  tratamientos-intimos_es:
    output: true
    permalink: /es/tratamientos-intimos/:slug/
  tratamientos-intimos_en:
    output: true
    permalink: /en/intimate-treatments/:slug/
  tecnologia_es:
    output: true
    permalink: /es/tecnologia/:slug/
  tecnologia_en:
    output: true
    permalink: /en/technology/:slug/

keep_files: [/img]

# Optimización de Sass
sass:
  style: compressed
  sourcemap: never

# Optimización HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

# Whitelist
whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag


include: ['_redirects']

# Redirecciones
redirect_from:
  enabled: true
  strip_index: true
  collections: true
  default_lang: "es"
  lang_keys: ["es", "en"]
  collections_from_prefix: false