baseurl: ''
url: 'https://dratatianaleal.com'
name: Tatiana Leal
email: asistentetatianaleal@gmail.com
maps: https://maps.app.goo.gl/bvbNFb82J7X3s1q16
direccion: "Torre Magna PI, Av Suba #114 - 59 Piso 6, Cons G14, Bogotá"
telefono: 3222010384
author:
  name: Tatiana Leal
  email: asistentetatianaleal@gmail.com
  instagram: https://www.instagram.com/dratatianaleal/
  facebook: https://www.facebook.com/Dra.TatianaLealSandoval
  youtube: https://www.youtube.com/channel/UCxF-X7in4xUFxYYwCMyC5OQ
  job_title: "Especialista en medicina estética y láser"
  bio: "La Dra. Tatiana Leal es una destacada especialista en Medicina Estética..."

title: Doctora Tatiana Leal
logo: /img/logo-tatiana-leal.webp

markdown: kramdown

publisher:
  name: Tatiana Leal
  logo: /img/logo-tatiana-leal.webp

# Configuración de idiomas
language: "es"
default_lang: "es"
languages: ["es", "en"]
exclude_from_localization: ["css", "img", "js"]

# Configuración de URLs y colecciones
permalink: /:lang/:slug/

collections:
  posts:
    output: true
    permalink: /es/blog/:title/ # Cambia esto
    defaults:
      - scope:
          path: "_posts/es"
          type: "posts"
        values:
          permalink: /es/blog/:title/
      - scope:
          path: "_posts/en"
          type: "posts"
        values:
          permalink: /en/blog/:title/
  tratamientos-faciales_es:
    output: true
    permalink: /es/tratamientos-faciales/:slug/
  tratamientos-faciales_en:
    output: true
    permalink: /en/facial-treatments/:slug/
  tratamientos-corporales_es:
    output: true
    permalink: /es/tratamientos-corporales/:slug/
  tratamientos-corporales_en:
    output: true
    permalink: /en/body-treatments/:slug/
  tratamientos-intimos_es:
    output: true
    permalink: /es/tratamientos-intimos/:slug/
  tratamientos-intimos_en:
    output: true
    permalink: /en/intimate-treatments/:slug/
  tecnologia_es:
    output: true
    permalink: /es/tecnologia/:slug/
  tecnologia_en:
    output: true
    permalink: /en/tegnology/:slug/

# Valores por defecto
defaults:
  - scope:
      path: ""
    values:
      lang: "es"
      layout: "default"
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      path: "_posts/es"
    values:
      lang: "es"
      layout: "articulo"
  - scope:
      path: "_posts/en"
    values:
      lang: "en"
      layout: "articulo"
  - scope:
      path: ""
      type: "tratamientos-faciales_es"
    values:
      lang: "es"
      layout: "servicios"
  - scope:
      path: ""
      type: "tratamientos-faciales_en"
    values:
      lang: "en"
      layout: "servicios"
  - scope:
      path: ""
      type: "tratamientos-corporales_es"
    values:
      lang: "es"
      layout: "servicios"
  - scope:
      path: ""
      type: "tratamientos-corporales_en"
    values:
      lang: "en"
      layout: "servicios"
  - scope:
      path: ""
      type: "tratamientos-intimos_es"
    values:
      lang: "es"
      layout: "servicios"
  - scope:
      path: ""
      type: "tratamientos-intimos_en"
    values:
      lang: "en"
      layout: "servicios"
  - scope:
      path: ""
      type: "tecnologia_es"
    values:
      lang: "es"
      layout: "servicios"
  - scope:
      path: ""
      type: "tecnologia_en"
    values:
      lang: "en"
      layout: "servicios"

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

# Plugins
plugins:
  - jekyll-redirect-from

# Whitelist
whitelist:
  - jekyll-redirect-from