name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: false
    
    - name: Install dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle lock --add-platform x86_64-linux  # Agregar esta línea
        bundle install
    
    - name: Build site
      run: bundle exec jekyll build
      env:
        JEKYLL_ENV: production
    
    - name: Deploy
      if: success() && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        enable_jekyll: false